const mongoose=require ('mongoose')
const userSchema=new mongoose.Schema(
   {
   username:{
        type:String,
        required:true,
        maxLength:50,
    },
    password:{
        type:String,
        required:true,
        maxLength:50
    },
    posts:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Posts",
    }],
    likes:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Likes",
    }],
    comments:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Comments",
    }],
    createdAt:{
        type:Date,
        required:true,
        default:Date.now()
    },
   }
)
module.exports=mongoose.model("Users",userSchema)